version: '3'
services:
    web:
        container_name: omoti-web
        build:
            context: ./web
            dockerfile: Dockerfile
        volumes:
            - ./web/src:/usr/src/app/
        working_dir: /usr/src/app/account-book
        command: sh -c "yarn start"
        ports:
            - 3000:3000
        tty: true
        networks:
            - backend
    api:
        container_name: omoti-api
        build:
            context: ./api
            dockerfile: Dockerfile
        env_file: ./api/app.env
        tty: true
        volumes:
            - ./api/src:/src
        ports:
            - 3001:3000
        working_dir: /src
        depends_on:
            - db
        networks:
            - backend
        command: npm run dev
    db:
        image: mysql:5.7
        container_name: omoti-db
        env_file: ./db/mysql.env
        volumes:
            - account-book-db:/var/lib/mysql:delegated
            - ./db/conf:/etc/mysql/conf.d/:ro
        ports:
            - 3306:3306
        networks:
            - backend

networks:
    backend:

volumes:
    account-book-db:
        driver: local
