version: '3'
services:
    web:
        container_name: react
        build:
            context: ./web
            dockerfile: Dockerfile
        volumes:
            - ./web:/usr/src/app
        command: sh -c "cd /usr/src/app && yarn start"
        ports:
            - 3000:3000
        tty: true
        networks:
            - backend
    app:
        container_name: nodejs
        build:
            context: ./app
            dockerfile: Dockerfile
        env_file: ./app/app.env
        tty: true
        volumes:
            - ./app/src:/src
        ports:
            - 3001:3000
        working_dir: /src
        depends_on:
            - db
        networks:
            - backend
        command: npm run dev
    db:
        image: mysql:5.7
        container_name: mysql
        env_file: ./db/mysql.env
        volumes:
            - account-book-db:/var/lib/mysql:delegated
            # - ./db/initdb.d:/docker-entrypoint-initdb.d
            - ./db/conf:/etc/mysql/conf.d/:ro
        ports:
            - 3306:3306
        networks:
            - backend

networks:
    backend:

volumes:
    account-book-db:
        driver: local
